Issue #1 - Migration from pages router to app router
ThEditor/nex pull request #4
Opened 2023-10-23 12:24 UTC by Anantu05

# Migration to App Router

This pull request addresses issue #1 by migrating the Nex music player application from the "pages router" to the "app router." This change helps us take advantage of the latest Next.js features and improves the overall maintainability and performance of Nex. 

In this process, `_app.tsx` and `_document.tsx` have been merged into `layout.tsx` file in the root directory of the app folder, and `404.tsx` has been replaced with the new convention - `not-found.tsx`. Some components have been added with `use client;` directive in order to use the new `router()` router instance and `usePathame()` function from `next/navigation` instead of the old router instance from `next/router`, both of which can only be used in the client side.

In addition to the migration, the `SEO` page has been replaced with the new built-in `Metadata` API to export metadata easily inside the app router.

Every `page` inside the app router has been split into two files - `layout.tsx` and `page.tsx`. `layout.tsx` is where every client side operation takes place and `page.tsx` is where server side operations take place. For now, the only server side operation in `page.tsx` files is the export of metadata using Metadata API. A void function has been written in order to bypass the error of not exporting a react component in the file. This void function can be used for future server side features as well.

# Screenshots
The improved not-found page
![localhost_3000_example](https://github.com/ThEditor/nex/assets/70461479/7f1af58e-d63d-4b1b-8de2-9dc39775a9bf)

2023-10-23 13:02 UTC, ThEditor requested changes
The code seems to default towards client-side components which is against the app router convention, hence, try to default to server-side pages and server-side components. If it's not possible to implement it as server-side then try to go for `'use client'`

2023-10-23 13:02 UTC, ThEditor commented on src/app/account/layout.tsx
> +'use client';
Do not make pages client-side which can be server-side.
Try to implement pages in server-side if possible. If not, then convert them to client-side.

2023-10-23 13:02 UTC, ThEditor commented on src/app/login/layout.tsx
> +'use client';
Though the file uses "useEffect", all it does is redirect the user if they're already signed in. Try to stay on server-side and redirect.
Refer: [NextJS Redirect Stackoverflow](https://stackoverflow.com/questions/58173809/next-js-redirect-from-to-another-page)

2023-10-31 17:18 UTC, OneRandom1509 commented on src/app/account/layout.tsx
> +'use client';
Alright, I'll make the updates in the upcoming PR

2023-10-31 17:19 UTC, OneRandom1509 commented on src/app/login/layout.tsx
> +'use client';
Updates coming up in the next PR

2023-10-31 17:37 UTC, OneRandom1509 commented
The new commits have made all the pages to be server-side and components to be server-side, except the sidebar and the carousel as it needs the user interactivity in order for it to work. All the above commented required changes have been made in a proper manner too.

2023-10-31 18:02 UTC, ThEditor approved these changes
After discussing this further on discord, I'm merging these changes.

2023-10-31 18:04 UTC, merged